# Generated by Django 3.0.2 on 2020-02-26 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=15)),
                ('quantity', models.IntegerField(default=0)),
                ('priceByDefault', models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('sellPrice', models.IntegerField(default=1)),
                ('imei', models.CharField(max_length=15)),
                ('custName', models.CharField(max_length=50)),
                ('custAdd', models.TextField(max_length=100)),
                ('cusPhone', models.CharField(blank=True, max_length=11)),
                ('custEmail', models.EmailField(blank=True, max_length=254)),
                ('note', models.TextField(blank=True, max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Manufacturer'),
        ),
    ]
